### ISSUE TITLE
VM getting no responds when trying to run "python main.py --find_client --service IOBluetoothHCIController"

### ISSUE THREAD

**Issue by fatgrass** [seclab-ucr/SyzGen_setup#2]
After add some debug message,VM will not respond after command **sudo dtrace -w -n "BEGIN{ breakpoint(); }"** executed.
It's triggered in function setup_debugger:
```python
def setup_debugger():
    subprocess.run(["ssh", getRemoteAddr(), "sudo dtrace -w -n \"BEGIN { breakpoint(); }\""])
    # time.sleep(10)  # wait 10s to make it taking effect
    logger.debug("suspend VM")
    return run_debugger(getConfigKey("kernel"))
```

In my case,when subprocess.run executed,vm will freeze,and subprocess.run function will not return,so there is no chance to execute run_debugger function.

**Comment by fatgrass** [comment]
Perhaps using subprocess.Popen can solve this problem:
```python
def setup_debugger():
    #subprocess.run(["ssh", getRemoteAddr(), "sudo dtrace -w -n \"BEGIN { breakpoint(); }\""])
    subprocess.Popen(["ssh", getRemoteAddr(), "sudo dtrace -w -n \"BEGIN { breakpoint(); }\""],
                    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    time.sleep(10)  # wait 10s to make it taking effect
    logger.debug("suspend VM")
    return run_debugger(getConfigKey("kernel"))
```

**Comment by CvvT** [comment]
Thanks for your interest and help. I'm currently working on refactoring the whole project and unfortunately won't have spare time to fix the old code.

As for this particular problem you encountered, could you elaborate a little bit more? The purpose of this command is to pause the execution of the VM and only then the debugger can connect to it. Thus, it is normal this command shows no response from VM.

**Comment by fatgrass** [comment]
Thanks for your reply.
I think subprocess.run is executed synchronously,and in my case "sudo dtrace -w -n \"BEGIN { breakpoint(); }" command run in guest OS will not finish immediately,so subprocess.Popen will keep waiting.
subprocess.Popen is executed asynchronously and will return immediately,so subsequent code can be executed.

**Comment by CvvT** [comment]
You're right, but I believe it is okay to execute this command synchronously because it would eventually finish due to disconnection from the VM. We run the command via ssh.

**Comment by owiofwm2i** [comment]
> Thanks for your reply. I think subprocess.run is executed synchronously,and in my case "sudo dtrace -w -n "BEGIN { breakpoint(); }" command run in guest OS will not finish immediately,so subprocess.Popen will keep waiting. subprocess.Popen is executed asynchronously and will return immediately,so subsequent code can be executed.

Hi bro, do you have any other contact information? I want to ask some questions about running, here is my [tg link](https://t.me/thisisan_account) thank you very much
