### ISSUE TITLE
simgr = simgr.step() raise "unsupported operand type(s) for +: 'int' and 'str'" error 

### ISSUE THREAD

**Issue by owiofwm2i** [seclab-ucr/SyzGen_setup#6]
Hi sir
nowdays i'm learning your project ,but when i do run the cmd `--find_client` or `--find_table`, in`self.execute` func,after running simgr = `simgr.step()` several times, an error will be raised, and I don't know how to debug(I've tried for a few days, but can't figure out what's wrong). Is it related to my system environment? My host is 11.4 and my virtual machine is 10.15.6

**Comment by CvvT** [comment]
Hi,

It would be great if you could show me the full backtrace.

**Comment by owiofwm2i** [comment]
> 

solved thank you
